     name: Deploy Hugo to GitHub Pages
     on:
       push:
         branches: [main]
     jobs:
       deploy:
         runs-on: ubuntu-latest
         steps:
           - name: Checkout
             uses: actions/checkout@v4
             with:
               submodules: recursive  # 包含主题子模块 [[4,14]]
               
           - name: Setup Hugo
             uses: peaceiris/actions-hugo@v2
             with:
               hugo-version: '0.144.2'  # 指定 Hugo 版本 [[1,14]]
               
           - name: Build
             run: hugo --minify --gc  # 生成静态文件到 public/ [[1,4]]
             
           - name: Deploy
             uses: peaceiris/actions-gh-pages@v3
             with:
               github_token: ${{ secrets.GITHUB_TOKEN }}
               publish_dir: ./public
               publish_branch: gh-pages  # 部署到 Pages 仓库的 gh-pages 分支 [[1,14]]